name: Deploy Auth Service

on:
  push:
    branches:
      - main
    paths:
      - "auth-service/**"

jobs:
  call-dockerhub-build:
    uses: ./.github/workflows/resuable-workflow.yml
    with:
      service_name: auth-service
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
